/**
 *
 * @author Rifqi Makarim
 */


public class Calculator extends javax.swing.JFrame {

    // Variable 
    double NumEntered1;
    double NumEntered2;
    double resultCal;
    String operator;
    
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LabelText = new javax.swing.JLabel();
        Result = new javax.swing.JTextField();
        CButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        EmojiButton = new javax.swing.JButton();
        LeftArrowButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        ModuloButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        CommasButton = new javax.swing.JButton();
        DivisionButton = new javax.swing.JButton();
        MultipleButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();
        PlusButton = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelText.setText("CALCULATOR");

        Result.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        CButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CButton.setText("C");
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });

        SevenButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SevenButton.setText("7");
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });

        FourButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FourButton.setText("4");
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });

        OneButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        OneButton.setText("1");
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });

        EmojiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmojiButton.setText("˃ᴗ˂");

        LeftArrowButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LeftArrowButton.setText("<-");
        LeftArrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftArrowButtonActionPerformed(evt);
            }
        });

        EightButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EightButton.setText("8");
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });

        FiveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FiveButton.setText("5");
        FiveButton.setToolTipText("");
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });

        TwoButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TwoButton.setText("2");
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });

        ZeroButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ZeroButton.setText("0");
        ZeroButton.setToolTipText("");
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });

        ModuloButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModuloButton.setText("%");
        ModuloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuloButtonActionPerformed(evt);
            }
        });

        NineButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NineButton.setText("9");
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });

        SixButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SixButton.setText("6");
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });

        ThreeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ThreeButton.setText("3");
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });

        CommasButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CommasButton.setText(".");
        CommasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommasButtonActionPerformed(evt);
            }
        });

        DivisionButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DivisionButton.setText("/");
        DivisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionButtonActionPerformed(evt);
            }
        });

        MultipleButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MultipleButton.setText("×");
        MultipleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultipleButtonActionPerformed(evt);
            }
        });

        MinusButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MinusButton.setText("-");
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        PlusButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlusButton.setText("+");
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        EqualsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EqualsButton.setText("=");
        EqualsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setText("Created by @RifqiMakarim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LeftArrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModuloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MultipleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmojiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CommasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Result))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelText)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeftArrowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModuloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultipleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmojiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>                        
    
    private void EnterNum( String number ) 
    {
        String nums = Result.getText()+ number;
        Result.setText(nums);
    }
    
    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void LeftArrowButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String backspace = null;
        if(Result.getText().length() > 0)
        {
            StringBuilder bs = new StringBuilder(Result.getText());
            bs.deleteCharAt(Result.getText().length()-1);
            backspace = bs.toString();
            Result.setText(backspace);
        }
        
    }                                               

    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        EnterNum("0");
    }                                          

    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        EnterNum("1");
    }                                         

    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        EnterNum("2");
    }                                         

    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        EnterNum("3");
    }                                           

    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        EnterNum("4");
    }                                          

    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        EnterNum("5");
    }                                          

    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        EnterNum("6");
    }                                         

    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        EnterNum("7");
    }                                           

    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        EnterNum("8");
    }                                           

    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        EnterNum("9");
    }                                          

    private void DivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        NumEntered1 = Double.parseDouble(Result.getText());
        Result.setText("");
        operator = "/";
    }                                              

    private void MultipleButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        NumEntered1 = Double.parseDouble(Result.getText());
        Result.setText("");
        operator = "*";
    }                                              

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        NumEntered1 = Double.parseDouble(Result.getText());
        Result.setText("");
        operator = "-";
    }                                           

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        NumEntered1 = Double.parseDouble(Result.getText());
        Result.setText("");
        operator = "+";
    }                                          

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Result.setText("");
        String a, b;
        a = String.valueOf(NumEntered1);
        b = String.valueOf(NumEntered2);
        a ="";
        b ="";
        
    }                                       

    private void CommasButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
        if(!Result.getText().contains("."))
        {
            Result.setText(Result.getText() + CommasButton.getText());
        }
    }                                            

    private void EqualsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        NumEntered2 = Double.parseDouble(Result.getText());
        
        if(operator == "+")
        {
            resultCal = NumEntered1 + NumEntered2;
            Result.setText(String.valueOf(resultCal));
        }
        
        else if ( operator == "-")
        {
            resultCal = NumEntered1 - NumEntered2;
            Result.setText(String.valueOf(resultCal));
        }
        
        else if( operator == "/")
        {
            resultCal = NumEntered1/NumEntered2;
            Result.setText(String.valueOf(resultCal));
            if(NumEntered2 == 0)
            {
                String error = "ERROR";
                Result.setText(error);
            }
        }
        
        else if ( operator == "*")
        {
            resultCal = NumEntered1*NumEntered2;
            Result.setText(String.valueOf(resultCal));
        }
        else if (operator == "%")
        {
            resultCal = NumEntered1%NumEntered2;
            Result.setText(String.valueOf(resultCal));
        }
    }                                            

    private void ModuloButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        NumEntered1 = Double.parseDouble(Result.getText());
        Result.setText("");
        operator = "%";
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CButton;
    private javax.swing.JButton CommasButton;
    private javax.swing.JButton DivisionButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EmojiButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JLabel LabelText;
    private javax.swing.JButton LeftArrowButton;
    private javax.swing.JButton MinusButton;
    private javax.swing.JButton ModuloButton;
    private javax.swing.JButton MultipleButton;
    private javax.swing.JButton NineButton;
    private javax.swing.JButton OneButton;
    private javax.swing.JButton PlusButton;
    private javax.swing.JTextField Result;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
